[package]
name = "sandcore_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = {workspace = true}
sandcore_core = {workspace = true}