[package]
name = "sandcore_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {workspace = true}
sandcore_world = {workspace = true}
sandcore_protocol = {workspace = true}
